import * as crypto from 'crypto';
import * as path from 'path';
import * as http from 'http';
import * as fs from 'fs';
import * as child_process from 'child_process';
import express from 'express';
import cors from 'cors';
import { WebSocketServer, WebSocket } from 'ws';
import {
  initDatabase, closeDatabase, insertEvent,
  getAgents, upsertAgent, getBudget, updateBudget,
  getWaves, upsertWave, getEvents,
} from './db/database';
import { createHealthRouter } from './routes/health';
import { createEventsRouter } from './routes/events';
import { createAgentsRouter } from './routes/agents';
import { createBudgetRouter } from './routes/budget';
import { createWavesRouter } from './routes/waves';
import { FileWatcherService } from './watchers/file-watcher';
import { GitWatcherService } from './watchers/git-watcher';
import { EventCategory, type MissionControlEvent, type AgentInfo } from './types/events';

// ---------------------------------------------------------------------------
// Configuration — dynamic, driven by env vars and config file
// ---------------------------------------------------------------------------

const PORT = parseInt(process.env.MC_PORT || '4201', 10);
const SESSION_ID = process.env.MC_SESSION_ID || crypto.randomUUID();
const DB_PATH = process.env.MC_DB_PATH || path.resolve(__dirname, '../../data/mission-control.db');

// Resolve project root: MC_PROJECT_DIR > parent of .mission-control > cwd
function resolveProjectDir(): string {
  if (process.env.MC_PROJECT_DIR) return process.env.MC_PROJECT_DIR;
  // If we're inside .mission-control/, the project root is one level up
  const cwd = process.cwd();
  if (path.basename(cwd) === '.mission-control' || path.basename(cwd) === 'mission-control') {
    return path.dirname(cwd);
  }
  return cwd;
}

const PROJECT_DIR = resolveProjectDir();
const WATCH_DIR = process.env.MC_WATCH_DIR || path.resolve(PROJECT_DIR, '.team');
const GIT_CWD = process.env.MC_GIT_CWD || PROJECT_DIR;

// Auto-detect current git branch instead of hardcoding
function detectGitBranch(cwd: string): string {
  if (process.env.MC_GIT_BRANCH) return process.env.MC_GIT_BRANCH;
  try {
    const result = child_process.execSync('git rev-parse --abbrev-ref HEAD', {
      cwd,
      encoding: 'utf-8',
      timeout: 5000,
      stdio: ['pipe', 'pipe', 'pipe'],
    });
    return result.trim() || 'main';
  } catch {
    return 'main';
  }
}

const GIT_BRANCH = detectGitBranch(GIT_CWD);

function log(level: string, message: string): void {
  const entry = { level, message, timestamp: new Date().toISOString() };
  process.stdout.write(JSON.stringify(entry) + '\n');
}

// ---------------------------------------------------------------------------
// Load config file (generated by scaffold or manually)
// ---------------------------------------------------------------------------

interface ProjectConfig {
  sessionId?: string;
  projectName?: string;
  teamName?: string;
  agents?: Array<{ role: string; name: string; color: string; category: string }>;
  budget?: { total: number; currency: string; alertThreshold: number };
  waves?: Array<{ number: number; name: string; status: string; gate: string }>;
}

function loadConfig(): ProjectConfig {
  const configPaths = [
    path.resolve(process.cwd(), 'mission-control.config.json'),
    path.resolve(PROJECT_DIR, '.mission-control', 'mission-control.config.json'),
    path.resolve(PROJECT_DIR, 'mission-control.config.json'),
  ];

  for (const configPath of configPaths) {
    if (fs.existsSync(configPath)) {
      try {
        const raw = fs.readFileSync(configPath, 'utf-8');
        const config = JSON.parse(raw) as ProjectConfig;
        log('info', `Loaded config from ${configPath}`);
        return config;
      } catch (err) {
        const msg = err instanceof Error ? err.message : 'Unknown error';
        log('warn', `Failed to load config from ${configPath}: ${msg}`);
      }
    }
  }

  log('info', 'No config file found — using defaults');
  return {};
}

const projectConfig = loadConfig();

// ---------------------------------------------------------------------------
// App Setup
// ---------------------------------------------------------------------------

const app = express();
const server = http.createServer(app);

// Middleware
app.use(cors({ origin: true }));
app.use(express.json({ limit: '1mb' }));

// ---------------------------------------------------------------------------
// WebSocket Setup
// ---------------------------------------------------------------------------

const wss = new WebSocketServer({ noServer: true });
const wsClients = new Set<WebSocket>();

// Handle HTTP upgrade for WebSocket
server.on('upgrade', (request, socket, head) => {
  if (request.url === '/ws') {
    wss.handleUpgrade(request, socket, head, (ws) => {
      wss.emit('connection', ws, request);
    });
  } else {
    socket.destroy();
  }
});

wss.on('connection', (ws: WebSocket) => {
  wsClients.add(ws);
  log('info', `WebSocket client connected (total: ${wsClients.size})`);

  ws.on('close', () => {
    wsClients.delete(ws);
    log('info', `WebSocket client disconnected (total: ${wsClients.size})`);
  });

  ws.on('error', (err) => {
    log('error', `WebSocket error: ${err.message}`);
    wsClients.delete(ws);
  });

  // Send full snapshot so the dashboard populates immediately
  sendSnapshot(ws);
});

/**
 * Build and send a snapshot of all current state to a WebSocket client.
 * This is sent on every new connection so the dashboard has data immediately.
 */
function sendSnapshot(ws: WebSocket): void {
  try {
    const agents = getAgents();
    const budget = getBudget();
    const waves = getWaves();
    const recentEvents = getEvents({ limit: 50 });

    const snapshot: Record<string, unknown> = {
      type: 'snapshot',
      sessionId: SESSION_ID,
      projectName: projectConfig.projectName || projectConfig.teamName || 'Project',
      agents: agents.length > 0 ? agents : undefined,
      budget: budget || undefined,
      waves: waves.length > 0 ? waves : undefined,
      events: recentEvents.events,
      timestamp: new Date().toISOString(),
    };

    ws.send(JSON.stringify(snapshot));
    log('info', `Snapshot sent: ${agents.length} agents, ${waves.length} waves, ${recentEvents.events.length} events`);
  } catch (err) {
    const msg = err instanceof Error ? err.message : 'Unknown error';
    log('error', `Failed to send snapshot: ${msg}`);
  }
}

/**
 * Broadcast a message to all connected WebSocket clients.
 */
function broadcast(data: Record<string, unknown>): void {
  const message = JSON.stringify(data);
  for (const client of wsClients) {
    if (client.readyState === WebSocket.OPEN) {
      try {
        client.send(message);
      } catch (err) {
        const msg = err instanceof Error ? err.message : 'Unknown error';
        log('error', `Failed to send WS message: ${msg}`);
      }
    }
  }
}

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------

app.use('/api', createHealthRouter(wsClients, SESSION_ID));
app.use('/api', createEventsRouter(wsClients, broadcast, SESSION_ID));
app.use('/api', createAgentsRouter(wsClients, broadcast));
app.use('/api', createBudgetRouter(wsClients, broadcast));
app.use('/api', createWavesRouter(wsClients, broadcast));

// Config endpoint — frontend can fetch dynamic project settings
app.get('/api/config', (_req, res) => {
  const agents = getAgents();
  const budget = getBudget();
  const waves = getWaves();
  res.json({
    sessionId: SESSION_ID,
    projectName: projectConfig.projectName || projectConfig.teamName || 'Project',
    teamName: projectConfig.teamName || 'unknown',
    agents,
    budget,
    waves,
    watchDir: WATCH_DIR,
    gitBranch: GIT_BRANCH,
    projectDir: PROJECT_DIR,
  });
});

// Serve static files in production
const clientDistPath = path.resolve(__dirname, '../client/dist');
app.use(express.static(clientDistPath));

// SPA fallback: serve index.html for unmatched routes (except /api)
app.get('*', (req, res) => {
  if (req.path.startsWith('/api')) {
    res.status(404).json({ error: 'Not found' });
    return;
  }
  res.sendFile(path.join(clientDistPath, 'index.html'), (err) => {
    if (err) {
      res.status(404).json({ error: 'Client not built. Run: npm run build:client' });
    }
  });
});

// ---------------------------------------------------------------------------
// Initialize Services
// ---------------------------------------------------------------------------

// Ensure data directory exists
const dataDir = path.dirname(DB_PATH);
if (!fs.existsSync(dataDir)) {
  fs.mkdirSync(dataDir, { recursive: true });
}

// Initialize database
initDatabase(DB_PATH);

// Seed agents from config if database is empty
function seedFromConfig(): void {
  const existingAgents = getAgents();
  if (existingAgents.length === 0 && projectConfig.agents) {
    for (const agent of projectConfig.agents) {
      upsertAgent({
        role: agent.role,
        name: agent.name,
        color: agent.color,
        category: agent.category as AgentInfo['category'],
        status: 'idle',
      });
    }
    log('info', `Seeded ${projectConfig.agents.length} agents from config`);
  }

  const existingBudget = getBudget();
  if (!existingBudget && projectConfig.budget) {
    updateBudget({
      total: projectConfig.budget.total,
      spent: 0,
      currency: projectConfig.budget.currency,
      alertThreshold: projectConfig.budget.alertThreshold,
    });
    log('info', `Seeded budget from config: $${projectConfig.budget.total}`);
  }

  const existingWaves = getWaves();
  if (existingWaves.length === 0 && projectConfig.waves) {
    for (const wave of projectConfig.waves) {
      upsertWave({
        number: wave.number,
        name: wave.name,
        status: wave.status as 'pending' | 'active' | 'done',
        gate: wave.gate as 'pending' | 'pass' | 'fail',
      });
    }
    log('info', `Seeded ${projectConfig.waves.length} waves from config`);
  }
}

seedFromConfig();

// Event handler for watchers: store in DB + broadcast via WS
function handleWatcherEvent(event: MissionControlEvent): void {
  try {
    insertEvent(event);
    broadcast({ type: 'event', data: event });
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error';
    log('error', `Failed to handle watcher event: ${message}`);
  }
}

// Start file watcher (scans existing files on startup)
const fileWatcher = new FileWatcherService(
  { watchDir: WATCH_DIR, sessionId: SESSION_ID },
  handleWatcherEvent
);
fileWatcher.start();

// Start git watcher
const gitWatcher = new GitWatcherService(
  { cwd: GIT_CWD, branch: GIT_BRANCH, sessionId: SESSION_ID },
  handleWatcherEvent
);
gitWatcher.start();

// ---------------------------------------------------------------------------
// Start Server
// ---------------------------------------------------------------------------

server.listen(PORT, () => {
  log('info', `Mission Control backend running on port ${PORT}`);
  log('info', `Session: ${SESSION_ID}`);
  log('info', `Project: ${PROJECT_DIR}`);
  log('info', `Database: ${DB_PATH}`);
  log('info', `Watching: ${WATCH_DIR}`);
  log('info', `Git CWD: ${GIT_CWD} (branch: ${GIT_BRANCH})`);

  // Emit startup event
  const startupEvent: MissionControlEvent = {
    id: crypto.randomUUID(),
    timestamp: new Date().toISOString(),
    sessionId: SESSION_ID,
    source: { tool: 'mission-control', version: '1.0.0' },
    category: EventCategory.SYSTEM,
    type: 'server_start',
    severity: 'info',
    payload: {
      port: PORT,
      projectDir: PROJECT_DIR,
      watchDir: WATCH_DIR,
      gitBranch: GIT_BRANCH,
      teamName: projectConfig.teamName,
    },
  };
  handleWatcherEvent(startupEvent);
});

// ---------------------------------------------------------------------------
// Graceful Shutdown
// ---------------------------------------------------------------------------

function shutdown(signal: string): void {
  log('info', `Received ${signal}. Shutting down gracefully...`);

  // Stop watchers
  fileWatcher.stop();
  gitWatcher.stop();

  // Close WebSocket connections
  for (const client of wsClients) {
    try {
      client.close(1001, 'Server shutting down');
    } catch {
      // Ignore close errors
    }
  }
  wsClients.clear();

  // Close database
  closeDatabase();

  // Close HTTP server
  server.close(() => {
    log('info', 'Server closed');
    process.exit(0);
  });

  // Force exit after 5 seconds
  setTimeout(() => {
    log('warn', 'Forced shutdown after timeout');
    process.exit(1);
  }, 5000);
}

process.on('SIGINT', () => shutdown('SIGINT'));
process.on('SIGTERM', () => shutdown('SIGTERM'));

// Handle unhandled errors to prevent crashes
process.on('uncaughtException', (err) => {
  log('error', `Uncaught exception: ${err.message}`);
  log('error', err.stack || 'No stack trace');
});

process.on('unhandledRejection', (reason) => {
  const message = reason instanceof Error ? reason.message : String(reason);
  log('error', `Unhandled rejection: ${message}`);
});

export { app, server, wsClients, broadcast, SESSION_ID };
