import { getEvents, getAgents, getBudget, getWaves } from '../db/database';
import type { MissionControlEvent, AgentInfo, WaveInfo } from '../types/events';

/**
 * Generate a full session report in Markdown format from DB data.
 */
export function generateMarkdownReport(): string {
  const { events } = getEvents({ limit: 500 });
  const agents = getAgents();
  const budget = getBudget();
  const waves = getWaves();

  const lines: string[] = [];
  const now = new Date().toISOString();

  lines.push('# Mission Control Session Report');
  lines.push('');
  lines.push(`**Generated:** ${now}`);
  lines.push('');

  // --- Budget Section ---
  lines.push('## Budget Summary');
  lines.push('');
  if (budget) {
    const pct = budget.total > 0 ? ((budget.spent / budget.total) * 100).toFixed(1) : '0.0';
    lines.push(`| Metric | Value |`);
    lines.push(`|--------|-------|`);
    lines.push(`| Total Budget | $${budget.total.toFixed(2)} ${budget.currency} |`);
    lines.push(`| Spent | $${budget.spent.toFixed(2)} ${budget.currency} |`);
    lines.push(`| Remaining | $${(budget.total - budget.spent).toFixed(2)} ${budget.currency} |`);
    lines.push(`| Usage | ${pct}% |`);
    lines.push(`| Alert Threshold | ${(budget.alertThreshold * 100).toFixed(0)}% |`);
    if (budget.hardCap) {
      lines.push(`| Hard Cap | $${budget.hardCap.toFixed(2)} ${budget.currency} |`);
    }
  } else {
    lines.push('_No budget data available._');
  }
  lines.push('');

  // --- Waves Section ---
  lines.push('## Waves');
  lines.push('');
  if (waves.length > 0) {
    lines.push('| Wave | Name | Status | Gate |');
    lines.push('|------|------|--------|------|');
    for (const w of waves) {
      lines.push(`| ${w.number} | ${w.name} | ${formatStatus(w.status)} | ${formatGate(w.gate)} |`);
    }
  } else {
    lines.push('_No wave data available._');
  }
  lines.push('');

  // --- Agents Section ---
  lines.push('## Agents');
  lines.push('');
  if (agents.length > 0) {
    lines.push('| Role | Name | Status | Tokens | Cost | Current Task |');
    lines.push('|------|------|--------|--------|------|--------------|');
    for (const a of agents) {
      lines.push(
        `| ${a.role} | ${a.name} | ${formatAgentStatus(a.status)} | ${formatTokens(a.tokensUsed)} | $${(a.costUsd ?? 0).toFixed(2)} | ${a.currentTask ?? '-'} |`
      );
    }
  } else {
    lines.push('_No agent data available._');
  }
  lines.push('');

  // --- Events Section ---
  lines.push('## Recent Events');
  lines.push('');
  if (events.length > 0) {
    lines.push(`Showing last ${events.length} events.`);
    lines.push('');
    lines.push('| Time | Category | Type | Severity | Agent |');
    lines.push('|------|----------|------|----------|-------|');
    for (const e of events.slice(0, 100)) {
      const time = new Date(e.timestamp).toLocaleString();
      const agent = e.agent?.role ?? '-';
      lines.push(`| ${time} | ${e.category} | ${e.type} | ${formatSeverity(e.severity)} | ${agent} |`);
    }
    if (events.length > 100) {
      lines.push('');
      lines.push(`_...and ${events.length - 100} more events._`);
    }
  } else {
    lines.push('_No events recorded._');
  }
  lines.push('');

  // --- Event Stats ---
  lines.push('## Event Statistics');
  lines.push('');
  const categoryCounts = countBy(events, (e) => e.category);
  const severityCounts = countBy(events, (e) => e.severity);

  lines.push('### By Category');
  lines.push('');
  lines.push('| Category | Count |');
  lines.push('|----------|-------|');
  for (const [cat, count] of Object.entries(categoryCounts).sort((a, b) => b[1] - a[1])) {
    lines.push(`| ${cat} | ${count} |`);
  }
  lines.push('');

  lines.push('### By Severity');
  lines.push('');
  lines.push('| Severity | Count |');
  lines.push('|----------|-------|');
  for (const [sev, count] of Object.entries(severityCounts).sort((a, b) => b[1] - a[1])) {
    lines.push(`| ${sev} | ${count} |`);
  }
  lines.push('');

  lines.push('---');
  lines.push('_Report generated by Mission Control._');

  return lines.join('\n');
}

// --- Helpers ---

function formatStatus(status: WaveInfo['status']): string {
  const icons: Record<string, string> = { pending: 'Pending', active: 'Active', done: 'Done' };
  return icons[status] ?? status;
}

function formatGate(gate: WaveInfo['gate']): string {
  const icons: Record<string, string> = { pending: 'Pending', pass: 'Pass', fail: 'Fail' };
  return icons[gate] ?? gate;
}

function formatAgentStatus(status: AgentInfo['status']): string {
  const labels: Record<string, string> = { idle: 'Idle', active: 'Active', blocked: 'Blocked', done: 'Done' };
  return labels[status] ?? status;
}

function formatSeverity(severity: string): string {
  const labels: Record<string, string> = { info: 'Info', warn: 'Warn', error: 'Error', critical: 'Critical' };
  return labels[severity] ?? severity;
}

function formatTokens(n?: number): string {
  if (!n) return '0';
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}K`;
  return String(n);
}

function countBy<T>(items: T[], key: (item: T) => string): Record<string, number> {
  const counts: Record<string, number> = {};
  for (const item of items) {
    const k = key(item);
    counts[k] = (counts[k] || 0) + 1;
  }
  return counts;
}
