#!/usr/bin/env python3
"""
Amenthyx AI Teams — Enhanced PDF Activity Summary Generator v3.0
Usage: python PDF_GENERATOR.py <report_number> <project_name> [team_dir]

Enhanced with:
- Evidence summary section
- Commit activity log
- Test coverage metrics
- CI/CD validation status
- Kanban velocity metrics
"""

import sys
import os
import json

sys.stdout.reconfigure(encoding='utf-8')

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.colors import HexColor
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch
from datetime import datetime


def read_file_safe(path):
    if os.path.exists(path):
        with open(path, 'r', encoding='utf-8') as f:
            return f.read()
    return None


def count_kanban(team_dir):
    kanban = read_file_safe(os.path.join(team_dir, "KANBAN.md"))
    if kanban:
        return {
            "done": kanban.count("[x]"),
            "in_progress": kanban.count("[~]"),
            "in_review": kanban.count("[?]"),
            "backlog": kanban.count("[ ]"),
        }
    return {"done": 0, "in_progress": 0, "in_review": 0, "backlog": 0}


def discover_artifacts(team_dir):
    artifacts = []
    if os.path.exists(team_dir):
        for root, dirs, files in os.walk(team_dir):
            for f in files:
                if f.endswith(('.md', '.yaml', '.yml', '.json', '.py', '.pptx', '.pdf', '.log', '.xml', '.html')):
                    rel_path = os.path.relpath(os.path.join(root, f), team_dir)
                    artifacts.append(f".team/{rel_path}")
    return artifacts


def count_evidence(team_dir):
    """Count evidence artifacts by category."""
    evidence_dir = os.path.join(team_dir, "evidence")
    counts = {"manifests": 0, "builds": 0, "tests": 0, "screenshots": 0, "runtime": 0, "ci": 0, "total": 0}
    if os.path.exists(evidence_dir):
        for root, dirs, files in os.walk(evidence_dir):
            for f in files:
                counts["total"] += 1
                rel = os.path.relpath(root, evidence_dir)
                for key in counts:
                    if key != "total" and rel.startswith(key):
                        counts[key] += 1
    return counts


def count_commits(team_dir):
    """Parse commit log if available."""
    commit_log = read_file_safe(os.path.join(team_dir, "COMMIT_LOG.md"))
    if commit_log:
        lines = [l for l in commit_log.split('\n') if '|' in l and not l.strip().startswith('#') and not l.strip().startswith('|--')]
        return max(0, len(lines) - 1)
    return 0


def create_activity_pdf(report_num, project_name, activities=None, team_dir=".team"):
    reports_dir = os.path.join(team_dir, "reports")
    os.makedirs(reports_dir, exist_ok=True)
    filepath = os.path.join(reports_dir, f"activity_{report_num:03d}.pdf")

    doc = SimpleDocTemplate(filepath, pagesize=letter,
                            topMargin=0.75 * inch, bottomMargin=0.75 * inch)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle', parent=styles['Title'],
        textColor=HexColor('#1a1a2e'), fontSize=20, spaceAfter=12
    )
    heading_style = ParagraphStyle(
        'CustomHeading', parent=styles['Heading2'],
        textColor=HexColor('#00d2ff'), fontSize=14, spaceAfter=8
    )
    subheading_style = ParagraphStyle(
        'CustomSubheading', parent=styles['Heading3'],
        textColor=HexColor('#bb86fc'), fontSize=12, spaceAfter=6
    )
    body_style = ParagraphStyle(
        'CustomBody', parent=styles['Normal'],
        fontSize=10, spaceAfter=6, leading=14
    )
    small_style = ParagraphStyle(
        'Small', parent=styles['Normal'],
        fontSize=8, spaceAfter=4, leading=10, textColor=HexColor('#666666')
    )
    success_style = ParagraphStyle(
        'Success', parent=styles['Normal'],
        fontSize=10, spaceAfter=6, leading=14, textColor=HexColor('#00C853')
    )
    warn_style = ParagraphStyle(
        'Warning', parent=styles['Normal'],
        fontSize=10, spaceAfter=6, leading=14, textColor=HexColor('#FFC107')
    )
    error_style = ParagraphStyle(
        'Error', parent=styles['Normal'],
        fontSize=10, spaceAfter=6, leading=14, textColor=HexColor('#FF1744')
    )

    elements = []

    # ──────────────────────────────────────────────────────────────
    # Title
    # ──────────────────────────────────────────────────────────────
    elements.append(Paragraph(f"Project Activity Summary &mdash; Report #{report_num}", title_style))
    elements.append(Paragraph(f"{project_name} | {datetime.now().strftime('%Y-%m-%d %H:%M')}", body_style))
    elements.append(Paragraph("Generated by Amenthyx AI Teams v3.0 — Evidence-Driven Execution", small_style))
    elements.append(Spacer(1, 0.3 * inch))

    # ──────────────────────────────────────────────────────────────
    # Section 1: Executive Metrics
    # ──────────────────────────────────────────────────────────────
    elements.append(Paragraph("1. EXECUTIVE METRICS", heading_style))
    kanban = count_kanban(team_dir)
    total = kanban["done"] + kanban["in_progress"] + kanban["in_review"] + kanban["backlog"]
    evidence = count_evidence(team_dir)
    commits = count_commits(team_dir)

    metrics_data = [
        ["Metric", "Value"],
        ["Tasks Completed", str(kanban['done'])],
        ["Tasks In Progress", str(kanban['in_progress'])],
        ["Tasks In Review", str(kanban['in_review'])],
        ["Tasks Remaining", str(kanban['backlog'])],
        ["Total Tasks", str(total)],
        ["Completion %", f"{int(kanban['done'] / total * 100)}%" if total > 0 else "0%"],
        ["Evidence Artifacts", str(evidence['total'])],
        ["Atomic Commits", str(commits)],
    ]

    t = Table(metrics_data, colWidths=[3 * inch, 2 * inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), HexColor('#1a1a2e')),
        ('TEXTCOLOR', (0, 0), (-1, 0), HexColor('#00d2ff')),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 0.5, HexColor('#333333')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [HexColor('#f8f9fa'), HexColor('#ffffff')]),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 0.3 * inch))

    # ──────────────────────────────────────────────────────────────
    # Section 2: Evidence Summary
    # ──────────────────────────────────────────────────────────────
    elements.append(Paragraph("2. EVIDENCE SUMMARY", heading_style))
    evidence_categories = [
        ("Agent Manifests", evidence["manifests"]),
        ("Build Logs", evidence["builds"]),
        ("Test Results", evidence["tests"]),
        ("Screenshots", evidence["screenshots"]),
        ("Runtime Proofs", evidence["runtime"]),
        ("CI Validation", evidence["ci"]),
    ]
    for name, count in evidence_categories:
        style = success_style if count > 0 else warn_style
        elements.append(Paragraph(f"{name}: {count} artifacts", style))

    # Check for manifests
    manifest_dir = os.path.join(team_dir, "evidence", "manifests")
    if os.path.exists(manifest_dir):
        for mf in sorted(os.listdir(manifest_dir)):
            if mf.endswith('_manifest.md'):
                agent_name = mf.replace('_manifest.md', '').upper()
                elements.append(Paragraph(f"  Agent {agent_name}: manifest submitted", success_style))
    else:
        elements.append(Paragraph("No evidence manifests submitted yet.", warn_style))

    elements.append(Spacer(1, 0.2 * inch))

    # ──────────────────────────────────────────────────────────────
    # Section 3: Completed Activities
    # ──────────────────────────────────────────────────────────────
    elements.append(Paragraph("3. COMPLETED ACTIVITIES", heading_style))
    if activities:
        for activity in activities:
            ts = activity.get("time", "N/A")
            agent = activity.get("agent", "Unknown")
            desc = activity.get("description", "")
            result = activity.get("result", "Done")
            evidence_ref = activity.get("evidence", "")
            line = f"[{ts}] <b>{agent}</b>: {desc} &mdash; {result}"
            if evidence_ref:
                line += f" | Evidence: {evidence_ref}"
            elements.append(Paragraph(line, body_style))
    else:
        elements.append(Paragraph("No activities recorded yet. PM will populate as agents report.", body_style))

    elements.append(Spacer(1, 0.2 * inch))

    # ──────────────────────────────────────────────────────────────
    # Section 4: Test Coverage
    # ──────────────────────────────────────────────────────────────
    elements.append(Paragraph("4. TEST COVERAGE", heading_style))
    test_dir = os.path.join(team_dir, "evidence", "tests")
    test_layers = ["static", "unit", "integration", "e2e", "performance", "security", "release"]
    for layer in test_layers:
        layer_dir = os.path.join(test_dir, layer)
        if os.path.exists(layer_dir) and os.listdir(layer_dir):
            file_count = len(os.listdir(layer_dir))
            elements.append(Paragraph(f"{layer.upper()}: EXECUTED ({file_count} result files)", success_style))
        else:
            elements.append(Paragraph(f"{layer.upper()}: NOT YET RUN", warn_style))

    elements.append(Spacer(1, 0.2 * inch))

    # ──────────────────────────────────────────────────────────────
    # Section 5: CI/CD Status
    # ──────────────────────────────────────────────────────────────
    elements.append(Paragraph("5. CI/CD VALIDATION STATUS", heading_style))
    ci_dir = os.path.join(team_dir, "evidence", "ci")
    if os.path.exists(ci_dir) and os.listdir(ci_dir):
        for ci_file in sorted(os.listdir(ci_dir)):
            elements.append(Paragraph(f"Validated: {ci_file}", success_style))
    else:
        elements.append(Paragraph("GitHub Actions not yet validated locally with act.", warn_style))
        elements.append(Paragraph("DevOps agent must run: act push / act pull_request before pushing.", body_style))

    elements.append(Spacer(1, 0.2 * inch))

    # ──────────────────────────────────────────────────────────────
    # Section 6: Commit Activity
    # ──────────────────────────────────────────────────────────────
    elements.append(Paragraph("6. COMMIT ACTIVITY", heading_style))
    elements.append(Paragraph(f"Total tracked commits: {commits}", body_style))
    commit_log = read_file_safe(os.path.join(team_dir, "COMMIT_LOG.md"))
    if commit_log:
        for line in commit_log.split('\n')[:25]:
            if line.strip():
                elements.append(Paragraph(line.strip(), small_style))
    else:
        elements.append(Paragraph("Commit log not yet created. PM tracks atomic commits in COMMIT_LOG.md.", body_style))

    elements.append(Spacer(1, 0.2 * inch))

    # ──────────────────────────────────────────────────────────────
    # Section 7: In-Progress Activities
    # ──────────────────────────────────────────────────────────────
    elements.append(Paragraph("7. IN-PROGRESS ACTIVITIES", heading_style))
    status_file = read_file_safe(os.path.join(team_dir, "TEAM_STATUS.md"))
    if status_file:
        for line in status_file.split('\n'):
            if line.strip():
                elements.append(Paragraph(line.strip(), body_style))
    else:
        elements.append(Paragraph("Team status not yet populated.", body_style))

    elements.append(Spacer(1, 0.2 * inch))

    # ──────────────────────────────────────────────────────────────
    # Section 8: Key Decisions
    # ──────────────────────────────────────────────────────────────
    elements.append(Paragraph("8. KEY DECISIONS MADE", heading_style))
    decisions = read_file_safe(os.path.join(team_dir, "DECISION_LOG.md"))
    if decisions:
        for line in decisions.split('\n')[:30]:
            if line.strip():
                elements.append(Paragraph(line.strip(), body_style))
    else:
        elements.append(Paragraph("No decisions logged yet.", body_style))

    elements.append(Spacer(1, 0.2 * inch))

    # ──────────────────────────────────────────────────────────────
    # Section 9: Artifacts Produced
    # ──────────────────────────────────────────────────────────────
    elements.append(Paragraph("9. ARTIFACTS PRODUCED", heading_style))
    artifacts = discover_artifacts(team_dir)
    if artifacts:
        for artifact in artifacts[:50]:
            elements.append(Paragraph(artifact, small_style))
        if len(artifacts) > 50:
            elements.append(Paragraph(f"... and {len(artifacts) - 50} more artifacts", small_style))
    else:
        elements.append(Paragraph("No artifacts produced yet.", body_style))

    elements.append(Spacer(1, 0.2 * inch))

    # ──────────────────────────────────────────────────────────────
    # Section 10: Blockers & Risks
    # ──────────────────────────────────────────────────────────────
    elements.append(Paragraph("10. BLOCKERS & RISKS", heading_style))
    risks = read_file_safe(os.path.join(team_dir, "RISK_REGISTER.md"))
    if risks:
        for line in risks.split('\n')[:20]:
            if line.strip():
                elements.append(Paragraph(line.strip(), body_style))
    else:
        elements.append(Paragraph("No blockers or risks identified.", success_style))

    # Build
    doc.build(elements)
    print(f"PDF saved: {filepath}")
    return filepath


if __name__ == "__main__":
    report_num = int(sys.argv[1]) if len(sys.argv) > 1 else 1
    project_name = sys.argv[2] if len(sys.argv) > 2 else "Project"
    team_dir = sys.argv[3] if len(sys.argv) > 3 else ".team"

    # Try to load activities from a JSON file if provided
    activities = []
    activities_path = os.path.join(team_dir, "reports", "activities.json")
    if os.path.exists(activities_path):
        with open(activities_path, 'r', encoding='utf-8') as f:
            activities = json.load(f)
    else:
        activities = [
            {"time": datetime.now().strftime("%H:%M"), "agent": "PM",
             "description": "Project initialization", "result": "Complete",
             "evidence": ".team/evidence/manifests/PM_manifest.md"}
        ]

    create_activity_pdf(report_num, project_name, activities, team_dir)
